name: Build
on:
  push:
    paths:
      - '**/*.swift'
      - '**/*.cpp'
      - '**/*.mm'
      - '**/*.m'
      - '**/*.h'
      - '*.xcodeproj/**'
      - '*.xcworkspace/**'
      - '.github/workflows/continuous-integration-workflow-xcode-latest.yml'
      - '!Source/Data/**'
  pull_request:
    paths:
      - '**/*.swift'
      - '**/*.cpp'
      - '**/*.mm'
      - '**/*.m'
      - '**/*.h'
      - '*.xcodeproj/**'
      - '*.xcworkspace/**'
      - '.github/workflows/continuous-integration-workflow-xcode-latest.yml'
      - '!Source/Data/**'

jobs:
  build:
    name: Build and Test with Xcode
    strategy:
      matrix:
        os: [macos-15, macos-26]
    runs-on: ${{ matrix.os }}
    # env:
    #   DEVELOPER_DIR: /Applications/Xcode.app/Contents/Developer
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "^26.1.1"
      - name: Build McBopomofo Engine
        run: cmake -DENABLE_TEST=1 -S . -B build && cmake --build build -j
        working-directory: Source
      - name: Test McBopomofo Engine
        run: ctest --output-on-failure
        working-directory: Source/build
      - name: Build McBopomofo Engine (SIMD)
        run: cmake -DENABLE_TEST=1 -DENABLE_EXPERIMENTAL_SIMD_SUPPORT_NEON=1 -S . -B build-simd && cmake --build build-simd -j
        working-directory: Source
      - name: Test McBopomofo Engine (SIMD) 
        run: ctest --output-on-failure
        working-directory: Source/build-simd
      - name: Test CandidateUI
        run: swift test --enable-code-coverage
        working-directory: Packages/CandidateUI
      - name: Test OpenCCBridge
        run: swift test --enable-code-coverage
        working-directory: Packages/OpenCCBridge
      - name: Test BopomofoBraille
        run: swift test --enable-code-coverage
        working-directory: Packages/BopomofoBraille
      - name: Test NSStringUtils
        run: swift test --enable-code-coverage
        working-directory: Packages/NSStringUtils
      - name: Test ChineseNumbers
        run: swift test --enable-code-coverage
        working-directory: Packages/ChineseNumbers
      - name: Test RomanNumbers
        run: swift test --enable-code-coverage
        working-directory: Packages/RomanNumbers
      - name: Test McBopomofo
        run: xcodebuild -scheme McBopomofo -configuration Debug clean test
      - name: Build McBopomofo and McBopomofoInstaller 
        run: xcodebuild -scheme McBopomofoInstaller -configuration Release clean build
      - name: Test data files
        run: make check
        working-directory: Source/Data
      - name: "Collect test results"
        if: github.event_name == 'push'
        run: bash .github/collect_swift_coverage.sh
      - name: Create commit comment
        if: github.event_name == 'push'
        uses: peter-evans/commit-comment@v4
        with:
          body-path: 'codecov_comment.md'
