name: Build phrase database
on:
  push:
    paths:
      - 'Source/Data/**'
      - '.github/workflows/continuous-build-data.yml'
  pull_request:
    paths:
      - 'Source/Data/**'
      - '.github/workflows/continuous-build-data.yml'

jobs:
  build:
    name: Build phrase database
    runs-on: ubuntu-latest
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Unit test the curation library
        run: python3 -m unittest
        working-directory: Source/Data
      - name: Test data files
        run: make check
        working-directory: Source/Data
      - name: Build phrase database
        run: make
        working-directory: Source/Data
